# Generated by Django 6.0.1 on 2026-06-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Curso activo?'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cupo_disponible',
            field=models.IntegerField(verbose_name='Cupo disponible'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(upload_to='cursos/', verbose_name='Imagen del curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio (MXN)'),
        ),
    ]
